# -*- coding: utf-8 -*-
"""DataGeneration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oD6q6cXGtzLSb4qQmnrIE55khaw4p6aR
"""

import openai

openai.api_key = '' # Insert API Key

def prompt(condition):
    prompt = f"""
I want you to generate transcripts of conversations between patients and doctors.
The conversations will contain information about a patient being referred to a respiratory specialist.
The Markham Stouffville Hospital will make the referral.
To this end, the conversation should have the following information:
1) whether it is an urgent or a routine referral,
2) the date,
3) the referring physician (referring MD),
4) the MD phone number,
5) the CPSO (College of Physicians and Surgeons of Ontario) number,
6) the preferred language of the patient,
7) the name and number of the interpreter, if the patient needs one (optional),
8) one of either 'COPD Clinic with Respirologist Consultation' or 'Asthma Education Clinic with Asthma Educator (RRT),' and
9) the reason for the referral (in this case, the patient {condition}).

The above is the general referral information.
In terms of patient information, the conversation should contain the following:
1) Hospital MRN (medical record number),
2) Patient name (last name comma first name),
3) Date of birth (in day, month, year format),
4) Sex (female or male),
5) Ontario Health Card number,
6) Version Code,
7) WSIB number (Workplace Safety and Insurance Board),
8) Whether the patient is self-paying (or a refugee),
9) Address with Postal Code,
10) Telephone number (with an optional alternative number), and
11) Email

Ensure that the conversation between the patient and the doctor is not interrogative;
it should be free-flowing, such as a patient who came for a general consultation after which their physician recommends they see a specialist;
or an emergency room doctor urgently ushers their patient to a specialist.
Generate just one conversation.

"""
    return prompt

def generate_convo(condition):
    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a tool that generates patient-doctor conversations with the required specifications."},
            {"role": "user", "content": prompt(condition)}
        ],
        temperature=0.7,
        top_p=0.80,
        max_tokens=4096
    )
    convo = response.choices[0].message.content
    return convo

conditions = ["has asthma", "has COPD", "has a cough", "has shortness of breath", "is a smoker who smokes [insert a realistic number] packs per day"]

with open("conversations.txt", "w") as f:
    pass

with open("conversations.txt", "a") as f:
    for condition in conditions:
        print(f"Condition: {condition}", file=f)
        conversation = generate_convo(condition)
        print("Begin Conversation: \n", file=f)
        print(conversation, file=f)
        print("\nEnd Conversation", file=f)
        print("\n\n", file=f)

        print(f"Condition: {condition}")
        print("Begin Conversation: \n")
        print(conversation)
        print("\nEnd Conversation")
        print("\n\n")